name: run ci cd
run-name: ${{ github.actor }} is launching ci cd
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : install dependencies and build
        run: | 
        npm install 
        npm run build
       run: npm run e2e:headless
      - name : upload video
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with: 
          name: video
          path: cypress/videos
          if-no-files-found: ignore
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install 
      - run: npm run build