name: run ci cd
run-name: ${{ github.actor }} is launching ci cd
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install 
      - run: npm run build