name: Run complete workflow
run-name: ${{ github.actor }} is launching the complete cicd workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies and build
        run: | 
          npm install  
          npm run build
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} #changé si le package-lock.json change, vérif si le hash du cache a changé
  test:
    needs: build #depends on build job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} #changé si le package-lock.json change, vérif si le hash du cache a changé
      - run: npm run e2e:headless
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with: 
          name: e2e-test-video
          path: cypress/videos
          if-no-files-found: ignore
